apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: tomcat
    targetPort: 8080
    protocol: TCP
  selector:
    app: tomcat-app