apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
spec:
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-app
        image: alegend1988/sample_tomcat:v1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080